config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/promote/:id', to: 'admin#promote', as: :promote
  get 'admin/user_details/:id', to: 'admin#user_details', as: :user_details
  get 'admin/lock_user/:id', to: 'admin#lock_user', as: :admin_lock_user
  get 'admin/unlock_user/:id', to: 'admin#unlock_user', as: :admin_unlock_user

  resources :articles do
    member do
      put :clap
    end
  end


  resources :lists do
      resources :items do
        member do
          put :toggle
      end
    end
  end

  devise_for :users
  get 'welcome/index'
  get('profile', to: 'profiles#show', as: :profile)

  root to: "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :name, presence: true

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :require_login
  before_action :set_list, only: [:show, :edit, :update, :destroy]


  # GET /lists
  # GET /lists.json
  def index
      @lists = current_user.lists
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @item = Item.new
    @item.list = @list
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user = current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = current_user.lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, id: :list_name, placeholder: 'List Name' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', :back %>

app/views/lists/index.html.erb
<h2 class="text-center">My Lists</h2>

<div class = "table-responsive">
  <table class="table" id="listTable">
    <thead>
      <tr>
      </tr>
    </thead>

    <tbody>
      <% @lists.each do |list| %>
        <tr>
          <td id="listName"><%= link_to list.name, list %></td>
          <td id="reName"><%= link_to 'Rename List', edit_list_path(list), class: 'btn btn-primary btn-xs' %></td>
          <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


</div>

<br>

<%= link_to 'Create New List', new_list_path, class:"btn btn-default btn-sm text-center" %><br>
<%= link_to 'Back', :back, class: "btn btn-primary btn-sm dark-button text-center text-uppercase" %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', :back, class: 'btn btn-default btn-sm dark-button' %>

app/views/lists/show.html.erb
<h2 class="text-center"><%= @list.name %></h2>







<ul class="list-items">
  <% @list.items.each do |item| %>
    <li id="modifyItem-<%= item.id %>" class="item <%= 'completed' if item.completed %>">

      <%= item.description %>
      <%= link_to '<i class="glyphicon glyphicon-check"></i>'.html_safe, toggle_list_item_path(@list, item), method: :put, remote: true %>
      <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, list_item_path(@list, item), method: :delete, remote: true %>

    </li>
  <% end %>

</ul>

    <%= form_with model: [@list, @item], local: true do |form| %>
      <%= form.hidden_field :completed, value: false %>
      <%= form.text_field :description, placeholder: "Add to your list" %>
    <% end %>



    <%= link_to 'Edit', edit_list_path(@list), class: 'btn btn-success btn-sm' %>
    <%= link_to 'Back', :back, class:"btn btn-primary btn-sm dark-button text-center text-uppercase"  %>