config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/promote/:id', to: 'admin#promote', as: :promote
  get 'admin/user_details/:id', to: 'admin#user_details', as: :user_details
  get 'admin/lock_user/:id', to: 'admin#lock_user', as: :admin_lock_user
  get 'admin/unlock_user/:id', to: 'admin#unlock_user', as: :admin_unlock_user

  resources :articles do
    member do
      put :clap
    end
  end


  resources :lists do
      resources :items do
        member do
          put :toggle
      end
    end
  end

  devise_for :users
  get 'welcome/index'
  get('profile', to: 'profiles#show', as: :profile)

  root to: "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

# Create a search method for searching articles

  def self.search(str)
    if str
      Article.where("title LIKE '%#{str}%' OR content LIKE '%#{str}%'")
    else
      Article.all
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: [:show, :index]
  before_action :set_article, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params[:search])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    # Add the current logged in user to the Article
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clap
    @article = Article.find(params[:id])
    @article.claps += 1
    @article.save
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class='container articlesMain'>
  <div class='row'>
    <div class='col-md-12'>
      <div class='page-header'>
        <h1 class='articleTitle'>

          <% if current_page?(articles_path) %>
            <%= link_to article.title, article %><br>
            <% else %>
              <%= article.title %>
            <% end %>
          <small>
            by <%= article.user.firstname %> <%= article.user.lastname[0] %> ·
            <%= time_ago_in_words(article.created_at) %> ago
          </small>

        </h1>
      </div>
    </div>
  </div>
</div>

<div class="container articleContent">
  <% if current_page?(articles_path) %>
  <div class='row'>
    <div class='col-md-12 sidebar-box'>
  <%= article.content.html_safe %>
  <h5 class="read-more"><a href="<%= article_path(article) %>" class="button">Read More</a></h5>
    </div>
  </div>
    <% else %>

      <div class='col-md-12 sidebar-box'>
    <%= article.content.html_safe %>
      </div>

    <%= link_to "Claps <span class='badge claps'>#{article.claps}</span>".html_safe, clap_article_path(article), method: :put, class: 'btn btn-primary', remote: true %>
    <% end %>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="submitArticle actions pull-right">
    <%= form.submit %>
  </div>

  <div class="field articleTitle">
    <%= form.text_field :title, id: :article_title, placeholder: "Title" %>
  </div>

  <div class="field articleContent">
    <%= form.text_area :content, id: :article_content, class: 'tinymce', rows: 20, cols: 100 %>
  </div>

  <%= tinymce %>


  <div class="submitArticle actions pull-right">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', :back, class: "btn btn-primary btn-sm dark-button text-center text-uppercase" %>

app/views/articles/clap.js.erb
// jquery to add claps to articles

$('.claps').text('<%= @article.claps %>')

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', :back, class: "btn btn-primary btn-sm dark-button text-center text-uppercase" %>

app/views/articles/index.html.erb
<div class="container articlesMain">
  <div class="row">
    <div class="class col-md-12">

      <h1>Articles</h1>

      <%= form_tag articles_path, method: :get, class: "navbar-form navbar-left search-form" do %>
        <%= text_field_tag(
            :search,
            params[:search],
            placeholder: "Search Articles",
            class: "form-control"
        ) %>
      <% end %>
    </div>
  </div>

</div>

<%= render @articles %>

<%= link_to 'New Article', new_article_path %>
<%= link_to 'Back', :back %>




<!-- <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.user.email %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->

app/views/articles/new.html.erb
<div class='container-fluid newArticles'>
<h1 id="newArticlePage">New Article</h1>
</div>


<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<!-- call in _article.html.erb partial -->
<%= render @article %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", :back, class: "btn btn-primary btn-sm dark-button text-center text-uppercase"  %>
      <% if @article.user == current_user %>
        |
        <%= link_to 'Edit', edit_article_path(@article) %>
        |
        <%= link_to 'Delete', @article, method: :delete,
        data: { confirm: 'Are you sure?'} %>
        <% end %>
    </div>
  </div>
</div>