config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/promote/:id', to: 'admin#promote', as: :promote
  get 'admin/user_details/:id', to: 'admin#user_details', as: :user_details
  get 'admin/lock_user/:id', to: 'admin#lock_user', as: :admin_lock_user
  get 'admin/unlock_user/:id', to: 'admin#unlock_user', as: :admin_unlock_user

  resources :articles do
    member do
      put :clap
    end
  end


  resources :lists do
      resources :items do
        member do
          put :toggle
      end
    end
  end

  devise_for :users
  get 'welcome/index'
  get('profile', to: 'profiles#show', as: :profile)

  root to: "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<div class="adminScreen container">
  <div class="row">
    <div class="col-md-12" id="userStats">
      <h1>User Stats</h1>
      Users <span class='badge'><%= @users.count %></span>
      Articles <span class='badge'><%= @article_count %></span>
      Lists <span class='badge'><%= @list_count %></span>
      Items <span class='badge'><%= @item_count %></span>

      <h1>All Users</h1>

        <ul>
          <% @users.each do |user| %>
            <li>
              <%= link_to (user.firstname + " " + user.lastname), user_details_path(user), remote: true %> ·

              <% unless user.is_admin %>

              <!-- Adding 'remote: true to line below tells the view to expect an AJAX request' -->
                <%= link_to "Promote", promote_path(user), remote: true, id: "promote-#{user.id}" %>

                <% else %>
                  <strong>Admin</strong>
              <% end %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="userModal" tabindex="-1" role="dialog" aria-labelledby="userModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="userModalLabel">User Data</h3>
      </div>

      <div class="modal-body container-fluid">
        <h4 class="text-center" id="name">Firstname Lastname</h4>
          <table class="table table-responsive">
            <thead>
              <tr>
                <th>Email</th>
                <th>Articles</th>
                <th>Lists</th>
                <th>Items</th>
                <th>Admin?</th>
                <th>Last Login</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td id="email">test@test.com</td>
                <td id="articles">8</td>
                <td id="lists">5</td>
                <td id="items">15</td>
                <td id="is_admin">No</td>
                <td id="last_login">4 days ago</td>
              </tr>
            </tbody>
          </table>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a id='lock_button' href="#" data-remote="true"><button type="button" class="btn btn-success">Lock</button></a>
        <a id='unlock_button' href="#" data-remote="true"><button type="button" class="btn btn-warning">Unlock</button></a>
      </div>
    </div>
  </div>
</div>

app/views/admin/lock_user.js.erb
$('#userModal #lock_button').hide()
$('#userModal #unlock_button').show()

app/views/admin/promote.js.erb
// Some jquery to update the promote-user link to ADMIN text
$('#promote-<%= @user.id %>').replaceWith('<strong>ADMIN</strong>')

app/views/admin/unlock_user.js.erb
$('#userModal #lock_button').show()
$('#userModal #unlock_button').hide()

app/views/admin/user_details.js.erb
$('#userModal #name').text('<%= @user.firstname %> <%= @user.lastname %>')
$('#userModal #articles').text('<%= @user.articles.count %>')
$('#userModal #lists').text('<%= @user.lists.count %>')
$('#userModal #items').text('<%= @user.item_count %>')
$('#userModal #is_admin').text('<%= @user.is_admin ? "Yes": "No" %>')
$('#userModal #last_login').text('<%= last_login_text(@user) %>')

$('#userModal #lock_button').attr('href', '<%= admin_lock_user_path(@user) %>')
$('#userModal #unlock_button').attr('href', '<%= admin_unlock_user_path(@user) %>')

<% if @user.access_locked? %>
  $('#userModal #lock_button').hide()
  $('#userModal #unlock_button').show()
<% else %>
  $('#userModal #unlock_button').hide()
  $('#userModal #lock_button').show()
<% end %>

$('#userModal').modal('show')