config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/promote/:id', to: 'admin#promote', as: :promote
  get 'admin/user_details/:id', to: 'admin#user_details', as: :user_details
  get 'admin/lock_user/:id', to: 'admin#lock_user', as: :admin_lock_user
  get 'admin/unlock_user/:id', to: 'admin#unlock_user', as: :admin_unlock_user

  resources :articles do
    member do
      put :clap
    end
  end


  resources :lists do
      resources :items do
        member do
          put :toggle
      end
    end
  end

  devise_for :users
  get 'welcome/index'
  get('profile', to: 'profiles#show', as: :profile)

  root to: "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>listMaker</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato: 400' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Montserrat+Alternates: 300, 400, 500i' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-inverse navbar-fixed-top">
      <div class="container">
   <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>Menu<i class="fa fa-bars"></i>
          </button>

          <%= link_to raw('<span class="logo">list</span>Maker'), root_path, class: 'navbar-brand' %>

    </div>
        <ul class="nav navbar-nav navbar-right">
          <!-- Lists Dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Lists <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <%= render 'nav_link', text: 'New List', path: new_list_path %>
              <%= render 'nav_link', text: 'My Lists', path: lists_path %>
            </ul>
          </li>

          <!-- Blogs Dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blogs <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <%= render 'nav_link', text: 'Blogs', path: articles_path %>
              <%= render 'nav_link', text: 'New Blog', path: new_article_path %>
            </ul>

          </li>

          <% if user_signed_in?  %>
            <%= render 'nav_link', text: 'Admin', path: admin_path if current_user.is_admin %>
            <%= render 'nav_link', text: "Signed in as #{current_user.firstname}  #{current_user.lastname[0]}.", path: profile_path %>
            <%= render 'nav_link', text: 'Log Out', path: destroy_user_session_path, link_options: {method: :delete} %>

          <% else  %>
            <%= render 'nav_link', text: 'Log In', path: new_user_session_path %>
            <%= render 'nav_link', text: 'Sign Up', path: new_user_registration_path %>
          <% end %>
        </ul>

      </div>

    </nav>


<div class="container mainContent">
      <%= yield %>
      <p id="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

</div>


  </body>
</html>